### ISSUE TITLE
How to update methods for different hooks?

### ISSUE THREAD

**Issue by rohan-deshpande** [o3bvv/hg-slackhooks#1]
Heya! thanks for this. I've forked this repo as I've been forced to use mercurial at my current place of employment for a bit rather than git. 

The mercurial docs are pretty bad imo, do you know where I can find info on the arguments that get passed to your methods, ie., `pushhook` which gets fired on the `changegroup` hook. I would like to fire this only on `outgoing` but I get an error saying the arguments are incorrect. Just don't know how many or what args are passed from `outgoing`. Any ideas?

**Comment by o3bvv** [comment]
Hi,

Yes, docs are honestly weird. I had to sift tons of docs and mercurial sources to get some kind of understanding. I haven't been using hg since last march, so it can take some time for investigation.

So, quick answer is to define your hook via bare positional and keyword params like

```
def the_hook(*args, **kwargs): ...
```

and investigate what's passed into hook. You may need to clone mercurial sources to search what those mean. You may need to use some separate repo as a sandbox to prevent your target repo from piling up with test commits. 

Let me know, in case you get stuck with this.

Thanks.

**Comment by rohan-deshpande** [comment]
Thanks a lot man, @koomai who's also working with me has made some changes, after inspecting the args. Working as we want now, thanks again for this repo!

**Comment by o3bvv** [comment]
Nice to hear that. I'm glad it is helpful for you. Cheers!
